"""assign_client_assessment

Revision ID: 09eec2f410e1
Revises: e9140fc23be4
Create Date: 2026-09-26 18:42:26.215530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09eec2f410e1'
down_revision: Union[str, Sequence[str], None] = 'e9140fc23be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assign_client_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_type_id', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessmentcategory.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assign_client_assessments')
    # ### end Alembic commands ###
