"""adding_compliance_category

Revision ID: 2a1e649baf52
Revises: 5935d9b6e63d
Create Date: 2026-09-13 14:38:03.456885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1e649baf52'
down_revision: Union[str, Sequence[str], None] = '5935d9b6e63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliancecategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compliance_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliancecategory_id'), 'compliancecategory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliancecategory_id'), table_name='compliancecategory')
    op.drop_table('compliancecategory')
    # ### end Alembic commands ###
