"""assign_client_assessment - IV

Revision ID: 41592d46c7fb
Revises: fa794f8fb23f
Create Date: 2026-09-26 20:04:19.325250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41592d46c7fb'
down_revision: Union[str, Sequence[str], None] = 'fa794f8fb23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
