"""authentication_implementation_I

Revision ID: 7fb80c4c5aec
Revises: 99f19afa33ff
Create Date: 2026-09-14 19:40:10.557283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fb80c4c5aec'
down_revision: Union[str, Sequence[str], None] = '99f19afa33ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_management', sa.Column('role', sa.String(length=30), nullable=False))
    op.drop_index(op.f('ix_employee_management_isadmin'), table_name='employee_management')
    op.create_index(op.f('ix_employee_management_role'), 'employee_management', ['role'], unique=False)
    op.drop_column('employee_management', 'isadmin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_management', sa.Column('isadmin', mysql.VARCHAR(length=30), nullable=False))
    op.drop_index(op.f('ix_employee_management_role'), table_name='employee_management')
    op.create_index(op.f('ix_employee_management_isadmin'), 'employee_management', ['isadmin'], unique=False)
    op.drop_column('employee_management', 'role')
    # ### end Alembic commands ###
