"""authentication_implementation

Revision ID: 99f19afa33ff
Revises: 5e4f04c1fbfa
Create Date: 2026-09-14 19:20:47.098703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99f19afa33ff'
down_revision: Union[str, Sequence[str], None] = '5e4f04c1fbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_management', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('employee_management', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('employee_management', 'isadmin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=30),
               nullable=False)
    op.create_index(op.f('ix_employee_management_isadmin'), 'employee_management', ['isadmin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_management_isadmin'), table_name='employee_management')
    op.alter_column('employee_management', 'isadmin',
               existing_type=sa.String(length=30),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('employee_management', 'updated_at')
    op.drop_column('employee_management', 'created_at')
    # ### end Alembic commands ###
