"""employee_management

Revision ID: a9c96bbd4e80
Revises: d9e02afdbbb3
Create Date: 2026-09-14 13:14:33.296890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9c96bbd4e80'
down_revision: Union[str, Sequence[str], None] = 'd9e02afdbbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_management', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('employee_management', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_management', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('employee_management', 'password')
    # ### end Alembic commands ###
