"""assign_client_assessment - IV

Revision ID: fa794f8fb23f
Revises: 79b8470becee
Create Date: 2026-09-26 20:04:13.759834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa794f8fb23f'
down_revision: Union[str, Sequence[str], None] = '79b8470becee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assign_client_assessments', sa.Column('assessment_Category_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('assign_client_assessments_ibfk_1'), 'assign_client_assessments', type_='foreignkey')
    op.create_foreign_key(None, 'assign_client_assessments', 'assessmentcategory', ['assessment_Category_id'], ['id'])
    op.drop_column('assign_client_assessments', 'assessment_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assign_client_assessments', sa.Column('assessment_type_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assign_client_assessments', type_='foreignkey')
    op.create_foreign_key(op.f('assign_client_assessments_ibfk_1'), 'assign_client_assessments', 'assessmentcategory', ['assessment_type_id'], ['id'])
    op.drop_column('assign_client_assessments', 'assessment_Category_id')
    # ### end Alembic commands ###
